### ISSUE TITLE
Third person perspective

### ISSUE THREAD

**Issue by zzlqwq** [gerkone/pyTORCS-docker#7]
I want to know how to switch the third person perspective and which parameter to configure

**Comment by gerkone** [comment]
Hey. iirc it's this line
https://github.com/gerkone/pyTORCS-docker/blob/d9c01a66c73f9637d93d20151ce8dc3cefd1b176/torcs/configs/config/graph.xml#L76
You can also cycle through the cameras in-game with F2, but I am not sure if it saves the configuration.

It has been quite some time since I worked on this so I am not really sure. Let me know if it helps

**Comment by zzlqwq** [comment]
It really worked, I am using this simulation environment for RL training. You have done a good job.

**Comment by gerkone** [comment]
Thanks. It's great that you are using this, please reach out if you get any interesting results.

I'll close this issue, but I am available if you have any further question.
